server:
  port: 8080

camel:
  springboot:
    name: IntegrationCamel
    main-run-controller: true
  component:
    amqp:
      enabled: true

amqp:
  uri: amqp://localhost:5672
  username: user
  password: changeit



